{
 "title": "Hashicorp Vault",
 "description": " Hashicorp Vault Metrics",
 "tags": [ "vault" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(vault_secret_kv_count,namespace)"
    }
   },
   { "name": "end_time", "label": "End Time", "query": "2024-12-31T11:59:59Z" },
   { "name": "start_time", "label": "Start Time", "query": "2024-01-01T00:00:00Z" },
   { "name": "entitlement", "label": "entitlement", "query": "100" }
  ]
 },
 "panels": [
  {
   "title": "Vault Clients & Identity Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Total Client Breakdown",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "clients", "text": "Clients", "type": "number" },
      { "selector": "non_entity_clients", "text": "Non Entity Clients", "type": "number" },
      { "selector": "entity_clients", "text": "Entity Clients", "type": "number" },
      { "selector": "non_entity_tokens", "text": "Non Entity Tokens", "type": "number" },
      { "selector": "secret_syncs", "text": "Secret Sync Clients", "type": "number" },
      { "selector": "acme_clients", "text": "ACME Clients", "type": "number" }
     ],
     "computed_columns": [
      { "selector": "$entitlement", "text": "Entitlement", "type": "string" }
     ],
     "parser": "backend",
     "root_selector": "data.total\n\n\n\n\n",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"data.total\"\n\n\n",
     "url": "/v1/sys/internal/counters/activity",
     "url_options": {
      "data": "",
      "headers": [],
      "method": "GET",
      "params": [
       { "key": "end_time", "value": "$end_time" },
       { "key": "start_time", "value": "$start_time" }
      ]
     }
    }
   ]
  },
  {
   "title": "Clients Breakdown by Month",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "columns": [
      { "selector": "counts", "text": "Count", "type": "string" },
      { "selector": "namespaces", "text": "Namespaces", "type": "string" },
      { "selector": "new_clients", "text": "New Clients", "type": "string" },
      { "selector": "timestamp", "text": "Time", "timestampFormat": "2006-01", "type": "timestamp" }
     ],
     "parser": "backend",
     "root_selector": "data.months\n\n\n\n\n",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"data.total\"\n\n\n",
     "url": "/v1/sys/internal/counters/activity",
     "url_options": {
      "data": "",
      "headers": [],
      "method": "GET",
      "params": [
       { "key": "end_time", "value": "$end_time" },
       { "key": "start_time", "value": "$start_time" }
      ]
     }
    }
   ]
  },
  {
   "title": "Total Clients Breakdown by Namespace",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "parser": "backend",
     "root_selector": "data.by_namespace\n\n\n\n",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"data.total\"\n\n\n",
     "url": "/v1/sys/internal/counters/activity",
     "url_options": {
      "data": "",
      "headers": [],
      "method": "GET",
      "params": [
       { "key": "end_time", "value": "$end_time" },
       { "key": "start_time", "value": "$start_time" }
      ]
     }
    }
   ]
  },
  {
   "title": "Total Client Breakdown by Namespace",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "clients", "text": "Clients", "type": "number" },
      { "selector": "non_entity_clients", "text": "Non Entity Clients", "type": "number" },
      { "selector": "entity_clients", "text": "Entity Clients", "type": "number" },
      { "selector": "secret_syncs", "text": "Secret Sync Clients", "type": "number" },
      { "selector": "acme_clients", "text": "ACME Clients", "type": "number" }
     ],
     "parser": "backend",
     "root_selector": "data.total\n\n\n\n\n",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"data.total\"\n\n\n",
     "url": "/v1/sys/internal/counters/activity",
     "url_options": {
      "data": "",
      "headers": [
       { "key": "X-Vault-Namespace", "value": "$namespace" }
      ],
      "method": "GET",
      "params": [
       { "key": "end_time", "value": "$end_time" }
      ]
     }
    }
   ]
  },
  {
   "title": "Namespace - Client Distribution by Auth Method/Mounts",
   "type": "table",
   "gridPos": { "h": 16, "w": 11, "x": 0, "y": 47 },
   "targets": [
    {
     "columns": [
      { "selector": "mount_accessor", "text": "mount_accessor", "type": "string" },
      { "selector": "mount_path", "text": "mount_path", "type": "string" },
      { "selector": "mount_type", "text": "mount_type", "type": "string" }
     ],
     "parser": "simple",
     "root_selector": "$.data.key_info.*",
     "source": "url",
     "type": "json",
     "url": "/v1/identity/entity-alias/id",
     "url_options": {
      "data": "",
      "headers": [
       { "key": "X-Vault-Namespace", "value": "$namespace" }
      ],
      "method": "GET",
      "params": [
       { "key": "list", "value": "true" },
       { "key": "end_time", "value": "$end_time" }
      ]
     }
    }
   ]
  },
  {
   "title": "Namespace - Client Distribution by Auth Method/Mounts",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 13, "x": 11, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "mount_accessor", "text": "mount_accessor", "type": "string" },
      { "selector": "mount_path", "text": "mount_path", "type": "string" },
      { "selector": "mount_type", "text": "mount_type", "type": "string" }
     ],
     "parser": "simple",
     "root_selector": "$.data.key_info.*",
     "source": "url",
     "type": "json",
     "url": "/v1/identity/entity-alias/id",
     "url_options": {
      "data": "",
      "headers": [
       { "key": "X-Vault-Namespace", "value": "$namespace" }
      ],
      "method": "GET",
      "params": [
       { "key": "list", "value": "true" },
       { "key": "end_time", "value": "$end_time" }
      ]
     }
    }
   ]
  },
  {
   "title": "Vault Clients Explorer with Client Attribution ( 1.18+)",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "csv_options": {
      "skip_empty_lines": false
     },
     "parser": "backend",
     "source": "url",
     "type": "csv",
     "uql": "parse-csv --delimiter \"\t\"",
     "url": "/v1/sys/internal/counters/activity/export",
     "url_options": {
      "data": "",
      "headers": [],
      "method": "GET",
      "params": [
       { "key": "end_time", "value": "$end_time" },
       { "key": "format", "value": "csv" },
       { "key": "start_time", "value": "$start_time" }
      ]
     }
    }
   ]
  },
  {
   "title": "Namespace Vault Clients Explorer v2 (For Vault Versions <1.17)",
   "type": "table",
   "description": "Combines two tables to show client attributions from export and entity-alias data",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "csv_options": {
      "skip_empty_lines": false
     },
     "parser": "backend",
     "source": "url",
     "type": "csv",
     "uql": "parse-csv --delimiter \"\t\"",
     "url": "/v1/sys/internal/counters/activity/export",
     "url_options": {
      "data": "",
      "headers": [],
      "method": "GET",
      "params": [
       { "key": "end_time", "value": "$end_time" },
       { "key": "format", "value": "csv" },
       { "key": "start_time", "value": "$start_time" }
      ]
     }
    },
    {
     "columns": [
      { "selector": "canonical_id", "text": "client_id", "type": "string" },
      { "selector": "custom_metadata", "text": "custom_metadata", "type": "string" },
      { "selector": "local", "text": "local", "type": "string" },
      { "selector": "mount_accessor", "text": "mount_accessor", "type": "string" },
      { "selector": "metadata", "text": "metadata", "type": "string" },
      { "selector": "mount_path", "text": "mount_path", "type": "string" },
      { "selector": "mount_type", "text": "mount_type", "type": "string" }
     ],
     "parser": "simple",
     "root_selector": "$.data.key_info.*",
     "source": "url",
     "type": "json",
     "url": "/v1/identity/entity-alias/id",
     "url_options": {
      "data": "",
      "headers": [
       { "key": "X-Vault-Namespace", "value": "$namespace" }
      ],
      "method": "GET",
      "params": [
       { "key": "list", "value": "true" },
       { "key": "end_time", "value": "$end_time" }
      ]
     }
    }
   ]
  },
  {
   "title": "Entities Alias Explorer (By Namepsace)",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 96 },
   "targets": [
    {
     "csv_options": {
      "skip_empty_lines": false
     },
     "json_options": {
      "columnar": false,
      "root_is_not_array": false
     },
     "parser": "simple",
     "root_selector": "$.data.key_info.*",
     "source": "url",
     "type": "json",
     "uql": "parse-csv --delimiter \"\t\"",
     "url": "/v1/identity/entity-alias/id",
     "url_options": {
      "data": "",
      "headers": [
       { "key": "X-Vault-Namespace", "value": "$namespace" }
      ],
      "method": "GET",
      "params": [
       { "key": "end_time", "value": "$end_time" },
       { "key": "list", "value": "true" }
      ]
     }
    }
   ]
  },
  {
   "title": "Entities Explorer ( by Namespace)",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 109 },
   "targets": [
    {
     "csv_options": {
      "skip_empty_lines": false
     },
     "json_options": {
      "columnar": false,
      "root_is_not_array": false
     },
     "parser": "simple",
     "root_selector": "$.data.key_info[*].*",
     "source": "url",
     "type": "json",
     "uql": "parse-csv --delimiter \"\t\"",
     "url": "/v1/identity/entity/id",
     "url_options": {
      "data": "",
      "headers": [
       { "key": "X-Vault-Namespace", "value": "$namespace" }
      ],
      "method": "GET",
      "params": [
       { "key": "end_time", "value": "$end_time" },
       { "key": "list", "value": "true" }
      ]
     }
    }
   ]
  },
  {
   "title": "Vault Entities Time Series Graph",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "vault_identity_num_entities{}", "legendFormat": "GET" }
   ]
  },
  {
   "title": "Active Clients Count (Current Month) Time-Series Graph",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vault_identity_entity_active_partial_month",
     "legendFormat": "SET"
    }
   ]
  },
  {
   "title": "Entity Count",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 11, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vault_identity_num_entities", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "(Estimated) Active Clients Count (Current Month)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 15, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vault_identity_entity_active_partial_month",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Monthly Client Count Time-Series Graph (Reported Beginning of every Month)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vault_identity_entity_active_monthly",
     "legendFormat": "SET"
    }
   ]
  },
  {
   "title": "Entity Alias Count",
   "type": "stat",
   "gridPos": { "h": 15, "w": 14, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(auth_method) (vault_identity_entity_alias_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Identity Entities Aliases by Method",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 10, "x": 14, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(auth_method)(vault_identity_entity_alias_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vault Clients Summary (Current Month)",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 162 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "clients", "text": "Clients", "type": "number" },
      { "selector": "non_entity_clients", "text": "Non Entity Clients", "type": "number" },
      { "selector": "entity_clients", "text": "Entity Clients", "type": "number" },
      { "selector": "non_entity_tokens", "text": "Non Entity Tokens", "type": "number" },
      { "selector": "secret_syncs", "text": "Secret Sync Clients", "type": "number" },
      { "selector": "acme_clients", "text": "ACME Clients", "type": "number" }
     ],
     "parser": "backend",
     "root_selector": "data\n\n\n\n\n",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"data.total\"\n\n\n",
     "url": "/v1/sys/internal/counters/activity/monthly",
     "url_options": {
      "data": "",
      "headers": [
       { "key": "X-Vault-Namespace", "value": "$namespace" }
      ],
      "method": "GET"
     }
    }
   ]
  }
 ]
}